---
name: AWS Build & Deployment

on:
  workflow_run:
    workflows: ["Versioning"]
    types: [requested]


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: das.singularitynet.io
  AWS_S3_BUCKET_KEY: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install function requirements
        run: |-
          pip3 install awscli
          for dir in */; do
            if [[ $dir != .* ]]; then
              pip3 install -r ./requirements.txt -t .
            fi
          done

      - name: Download DocumentDB pem
        run: |-
          for dir in */; do
            if [[ $dir != .* ]]; then
              wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
            fi
          done

      - name: Bundle function into a ZIP file
        run: |-
          for dir in */; do
            if [[ $dir != .* ]]; then
              FUNC_NAME=$(basename "$dir")

              zip -r $FUNC_NAME.zip .
            fi
          done

      - name: Push function to s3
        run: |-
          for dir in */; do
            if [[ $dir != .* ]]; then
              FUNC_NAME=$(basename "$dir")

              aws s3 cp ./$FUNC_NAME.zip s3://${{ env.AWS_S3_BUCKET }}/${{ env.AWS_S3_BUCKET_KEY }}/$FUNC_NAME.zip
            fi
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update lambda function
        run: |-
        for dir in */; do
          if [[ $dir != .* ]]; then
            FUNC_NAME=$(basename "$dir")

            aws lambda update-function-code --function-name  ${{ env.FUNC_NAME }} --s3-bucket ${{ env.AWS_S3_BUCKET }} --s3-key ${{ env.AWS_S3_BUCKET_KEY }}/${{ env.FUNC_NAME }}.zip --publish --region ${{ env.AWS_REGION }}
          fi
        done