---
name: Run Tests & Lint

on:
  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:
    inputs:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set dotenv
        run: cp .env.example .env

      - name: Install dependencies
        run: |-
          pip3 install -r requirements.txt
          pip3 install -r das-query-engine/requirements.txt

      - name: Run Lint & Tests
        run: make pre-commit
