---
name: Run Tests & Lint

on:
  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:
    inputs:

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Install dependencies
        run: |-
          pip3 install -r requirements.txt
          pip3 install -r das-query-engine/requirements.txt

  lint:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Perform Code Linting
        run: make lint

  unit-tests:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Execute Unit Test Suite
        run: make unit-tests

  coverage:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Generate Coverage Report
        run: make unit-tests-coverage

  integration-tests:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Perform Integration Testing
        run: make integration-tests
