---
name: Run Tests & Lint

on:
  workflow_call:

  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Perform Code Linting
        run: make lint

  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Install dependencies
        run: pip3 install -r das-query-engine/requirements.txt

      - name: Execute Unit Test Suite
        run: make unit-tests

  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Install dependencies
        run: pip3 install -r das-query-engine/requirements.txt

      - name: Generate Coverage Report
        run: make unit-tests-coverage

  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ^3.10
          cache: "pip"

      - name: Install dependencies
        run: pip3 install -r das-query-engine/requirements.txt

      - name: Set dotenv
        run: cp .env.example .env

      - name: Perform Integration Testing
        run: make integration-tests
