---
name: Vultr Build & Deployment

on:
  push:
    branches:
      - feat/deployment

env:
  DEPLOYMENT_FILE: das-function.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: das-servless-functions

      - name: Checkout das-infra-stack-vultr Repository
        uses: actions/checkout@v4
        with:
          repository: singnet/das-infra-stack-vultr
          path: das-infra-stack-vultr
          ref: master

      - name: Go to das-infra-stack-vultr
        run: cd ./das-infra-stack-vultr

      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull python3

      - name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f ${{ env.DEPLOYMENT_FILE }}

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Registry
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: push -f ${{ env.DEPLOYMENT_FILE }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} \
            -g ${{ secrets.OPENFAAS_GATEWAY }}

      - name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: deploy -f ${{ env.DEPLOYMENT_FILE }}
